"""Initial migration creating all tables

Revision ID: 981cbaae32a1
Revises: 
Create Date: 2026-02-12 23:20:18.584973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '981cbaae32a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('msisdn', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('pin', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ACTIVE', 'EXHAUSTED', 'DISABLED', name='account_status'), nullable=False),
    sa.Column('is_reseller', sa.Boolean(), nullable=False),
    sa.Column('balance_last', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_device_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('msisdn', 'batch_id', name='uq_msisdn_batch')
    )
    op.create_index(op.f('ix_accounts_batch_id'), 'accounts', ['batch_id'], unique=False)
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=False)
    op.create_index(op.f('ix_accounts_msisdn'), 'accounts', ['msisdn'], unique=False)
    op.create_index(op.f('ix_accounts_status'), 'accounts', ['status'], unique=False)
    op.create_table('servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('wait_between_retries', sa.Integer(), nullable=False),
    sa.Column('max_requests_queued', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_url'),
    sa.UniqueConstraint('port')
    )
    op.create_table('bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('step', sa.Enum('BOUND', 'OTP_REQUESTED', 'OTP_VERIFICATION', 'OTP_VERIFIED', 'TOKEN_LOGIN_FETCHED', 'LOGGED_OUT', name='binding_step'), nullable=False),
    sa.Column('is_reseller', sa.Boolean(), nullable=False),
    sa.Column('balance_start', sa.Integer(), nullable=True),
    sa.Column('balance_last', sa.Integer(), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('last_error_message', sa.String(length=255), nullable=True),
    sa.Column('token_login', sa.String(length=1024), nullable=True),
    sa.Column('token_location', sa.String(length=1024), nullable=True),
    sa.Column('token_location_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('bound_at', sa.DateTime(), nullable=False),
    sa.Column('unbound_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bindings_account_id'), 'bindings', ['account_id'], unique=False)
    op.create_index(op.f('ix_bindings_batch_id'), 'bindings', ['batch_id'], unique=False)
    op.create_index(op.f('ix_bindings_server_id'), 'bindings', ['server_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trx_id', sa.String(length=64), nullable=False),
    sa.Column('t_id', sa.String(length=64), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('binding_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('limit_harga', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('voucher_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PROCESSING', 'PAUSED', 'RESUMED', 'SUKSES', 'SUSPECT', 'GAGAL', name='transaction_status'), nullable=False),
    sa.Column('is_success', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('otp_required', sa.Boolean(), nullable=False),
    sa.Column('otp_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='transaction_otp_status'), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('resumed_at', sa.DateTime(), nullable=True),
    sa.Column('pause_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['binding_id'], ['bindings.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_batch_id'), 'transactions', ['batch_id'], unique=False)
    op.create_index(op.f('ix_transactions_binding_id'), 'transactions', ['binding_id'], unique=False)
    op.create_index(op.f('ix_transactions_server_id'), 'transactions', ['server_id'], unique=False)
    op.create_index(op.f('ix_transactions_t_id'), 'transactions', ['t_id'], unique=False)
    op.create_index(op.f('ix_transactions_trx_id'), 'transactions', ['trx_id'], unique=False)
    op.create_table('transaction_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('balance_start', sa.Integer(), nullable=True),
    sa.Column('balance_end', sa.Integer(), nullable=True),
    sa.Column('trx_idv_raw', sa.JSON(), nullable=True),
    sa.Column('status_idv_raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_snapshots_transaction_id'), 'transaction_snapshots', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_snapshots_transaction_id'), table_name='transaction_snapshots')
    op.drop_table('transaction_snapshots')
    op.drop_index(op.f('ix_transactions_trx_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_t_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_server_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_binding_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_batch_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_bindings_server_id'), table_name='bindings')
    op.drop_index(op.f('ix_bindings_batch_id'), table_name='bindings')
    op.drop_index(op.f('ix_bindings_account_id'), table_name='bindings')
    op.drop_table('bindings')
    op.drop_table('servers')
    op.drop_index(op.f('ix_accounts_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_msisdn'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_batch_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
