"""add processed reseller and token fields

Revision ID: c9de36a569ce
Revises: abbbf70fc779
Create Date: 2026-03-03 14:17:44.536226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c9de36a569ce'
down_revision: Union[str, Sequence[str], None] = 'abbbf70fc779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trx_id', sa.String(length=64), nullable=False),
    sa.Column('t_id', sa.String(length=64), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('binding_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('limit_harga', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('voucher_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PROCESSING', 'PAUSED', 'RESUMED', 'SUKSES', 'SUSPECT', 'GAGAL', name='transaction_status'), nullable=False),
    sa.Column('is_success', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('otp_required', sa.Boolean(), nullable=False),
    sa.Column('otp_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='transaction_otp_status'), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('resumed_at', sa.DateTime(), nullable=True),
    sa.Column('pause_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['binding_id'], ['bindings.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_binding_id'), ['binding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_server_id'), ['server_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_t_id'), ['t_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_trx_id'), ['trx_id'], unique=False)

    op.create_table('transaction_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('balance_start', sa.Integer(), nullable=True),
    sa.Column('balance_end', sa.Integer(), nullable=True),
    sa.Column('trx_idv_raw', sa.JSON(), nullable=True),
    sa.Column('status_idv_raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_snapshots_transaction_id'), ['transaction_id'], unique=False)

    op.drop_table('_alembic_tmp_accounts')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_processed', sa.Boolean(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_accounts_is_processed'), ['is_processed'], unique=False)

    with op.batch_alter_table('bindings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reseller', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('token_location', sa.String(length=500), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_orders_email'))
        batch_op.create_index(batch_op.f('ix_orders_email'), ['email'], unique=False)

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_servers_name'))
        batch_op.create_index(batch_op.f('ix_servers_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_name'))
        batch_op.create_index(batch_op.f('ix_servers_name'), ['name'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_email'))
        batch_op.create_index(batch_op.f('ix_orders_email'), ['email'], unique=1)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('bindings', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('token_location')
        batch_op.drop_column('is_reseller')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_is_processed'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('is_processed')

    op.create_table('_alembic_tmp_accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('msisdn', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('pin', sa.VARCHAR(length=20), nullable=True),
    sa.Column('balance_last', sa.INTEGER(), nullable=True),
    sa.Column('used_count', sa.INTEGER(), nullable=False),
    sa.Column('last_used_at', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'true'"), nullable=False),
    sa.Column('card_active_until', sa.VARCHAR(length=50), nullable=True),
    sa.Column('grace_period_until', sa.VARCHAR(length=50), nullable=True),
    sa.Column('expires_info', sa.VARCHAR(length=100), nullable=True),
    sa.Column('last_balance_response', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('msisdn', 'order_id', name=op.f('uq_msisdn_order'))
    )
    with op.batch_alter_table('transaction_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_snapshots_transaction_id'))

    op.drop_table('transaction_snapshots')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_trx_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_t_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_server_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_binding_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_batch_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))

    op.drop_table('transactions')
    # ### end Alembic commands ###
